
GET http://localhost:8080/api/v1/jobs/get/all HTTP/1.1

###

GET http://localhost:8080/api/v1/jobs/get/5f6c089dc1d0ea11c1f16dbe HTTP/1.1

###

POST http://localhost:8080/api/v1/jobs/post/one HTTP/1.1
content-type: application/json

{
        "position": "Senior Full Stack Developer",
        "company": "Framestore",
        "location": "London",
        "salary": 10000
}

###

PUT http://localhost:8080/api/v1/jobs/put/1000 HTTP/1.1


###

DELETE  http://localhost:8080/api/v1/jobs/delete/5f750deda66e7f2327c1c874 HTTP/1.1


###
